edit files
Tshepo45/Mobile-Version pull request #1
Opened 2022-04-27 09:55 UTC by Tshepo45

edit index.html file title
edit style.css property

2022-04-28 10:19 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @Tshepo45👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-28 10:19 UTC, thecodechaser commented on index.html
> +    <img class="my-logo" src="image/mylogo.png" alt="my logo">
- [ ] Please wrap your logo in the anchor tag, Logos are supposed to be links so users can use them to go to the home page by clicking on them.

2022-04-28 10:19 UTC, thecodechaser commented on index.html
>       <img src="image/Ellipse5.png" class="Ellipse5" alt="ellipse5">
- [ ] The images you are using here do not exist in your project, Please make sure you add these images in your project so they are visible on the page.

### See the image for reference 

![image](https://user-images.githubusercontent.com/83803414/165730449-4f11dbe9-8470-486b-8732-03815a91d421.png)

2022-04-28 10:19 UTC, thecodechaser commented on index.html
>       <img src="image/Ellipse5.png" class="Ellipse5" alt="ellipse5">
- [ ] The below code is not visible on this PR because the PR does not have that code as changed so I can not highlight the code. on line 28 please change the `<section>` tag with the `<main>` tag, It will make sure the code is semantic and follows best practices.

2022-04-28 10:19 UTC, thecodechaser commented on index.html
>    </header>
- [ ] For this project you are supposed to stick to the [Figma ](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=0%3A1) template as much as possible.
    - Please make sure all the images in the project are visible, Add all the images in the project directory.
    - Please add the hamburger icon and background images.
    - Please use the correct font-size, font-weight, and font-family for texts on the webpage.
    - Please make sure the social media icons are visible
    - Please make sure your design matches with the Figma design.

### Your design

![image](https://user-images.githubusercontent.com/83803414/165730972-b0bd06b7-f1e9-47a7-a87a-d8406fd0a6ee.png)

### Figma design

![image](https://user-images.githubusercontent.com/83803414/165731049-71625854-3d62-4853-a49a-5b0d664cb274.png)

2022-04-29 00:17 UTC, zieeco requested changes
Hi @Tshepo45 


Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the changes, however, there are some issues that you still need to work on to go to the next project, but you are almost there!


## To highlight 🎯

- No linter errors.✔️
- Nice design. ✔️
- Descriptive PR. ✔️


## Required Changes ♻️
- Please, kindly  fix the issues with your image link as required by the previous reviewer

![image](https://user-images.githubusercontent.com/59397159/165867333-b75a7cad-06a8-46b6-9ea7-af6fb7e237fb.png)




<img src="https://media0.giphy.com/media/8UGVQESpDMMQl7yd3F/giphy.gif"/>


## Optional suggestions
- N/A
**_Every comment with the **[OPTIONAL]** prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._**


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 10:48 UTC, danielufeli approved these changes
Hi @Tshepo45,

Great work on making the changes requested by the previous reviewer 👏
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![a](https://camo.githubusercontent.com/40c24648ada128030359495b9504e95985194c3f4bbeabf0485e740ecd253bcc/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f6a4a5143327075565a70544d4f34765573302f67697068792e676966)

## Highlights
- Nice commits messages✔️
- Descriptive PR ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @danielufeli in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-29 11:00 UTC, merged